/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package binarygame;
import java.awt.Color;
import java.util.Random;
import javax.swing.Timer; 

/**
 *
 * @author earlj
 */
public class GameFrame extends javax.swing.JFrame {
    private static final int TIME_PER_QUESTION = 30;
    private int currentDecimalValue;
    private int score = 0;
    private int totalQuestions = 0;
    private int timeLeft = TIME_PER_QUESTION;
    private final Random random = new Random();
    private Timer countdownTimer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameFrame.class.getName());

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        initTimer();
        loadNewQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        binaryLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        answerField = new javax.swing.JTextField();
        feedbackLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        timerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 6, 14));
        jPanel1.setForeground(new java.awt.Color(254, 232, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));

        titleLabel.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(254, 232, 1));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Binary To Decimal Quiz");

        binaryLabel.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        binaryLabel.setForeground(new java.awt.Color(254, 232, 1));
        binaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        binaryLabel.setText("--------");
        binaryLabel.setAutoscrolls(true);
        binaryLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 159, 23)));

        submitButton.setBackground(new java.awt.Color(0, 6, 14));
        submitButton.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        submitButton.setForeground(new java.awt.Color(254, 232, 1));
        submitButton.setText("Submit");
        submitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 159, 23)));
        submitButton.setContentAreaFilled(false);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(this::submitButtonActionPerformed);

        answerField.setBackground(new java.awt.Color(0, 6, 14));
        answerField.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        answerField.setForeground(new java.awt.Color(254, 232, 1));
        answerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerField.setText("jTextField1");
        answerField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 159, 23)));
        answerField.setCaretColor(new java.awt.Color(0, 6, 14));
        answerField.setDisabledTextColor(new java.awt.Color(0, 6, 14));
        answerField.setMargin(new java.awt.Insets(20, 20, 20, 20));
        answerField.setSelectedTextColor(new java.awt.Color(136, 4, 37));
        answerField.addActionListener(this::answerFieldActionPerformed);

        feedbackLabel.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        feedbackLabel.setForeground(new java.awt.Color(254, 232, 1));
        feedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        feedbackLabel.setText("Enter the decimal value");

        scoreLabel.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(254, 232, 1));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Score: 0 / 0");
        scoreLabel.setToolTipText("");

        newGameButton.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        newGameButton.setForeground(new java.awt.Color(254, 232, 1));
        newGameButton.setText("Reset");
        newGameButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 159, 23), 1, true));
        newGameButton.setContentAreaFilled(false);
        newGameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newGameButton.addActionListener(this::newGameButtonActionPerformed);

        timerLabel.setFont(new java.awt.Font("Rajdhani", 0, 28)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(254, 232, 1));
        timerLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(binaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(feedbackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(binaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(newGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(timerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 764, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
        // TODO add your handling code here:
        checkAnswer();
    }//GEN-LAST:event_answerFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        checkAnswer();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // TODO add your handling code here:
        resetGame();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void initTimer() {
        countdownTimer = new Timer(1000, e -> onTimerTick());
    }

    private void onTimerTick() {
        timeLeft--;
        updateTimerLabel();
        if (timeLeft <= 0) {
            timeExpired();
        }
    }

    private void updateTimerLabel() {
        timerLabel.setText("Time: " + timeLeft + "s");

        if (timeLeft > 5) {
            timerLabel.setForeground(new Color(84,193,230));
        } else if (timeLeft > 2) {
            timerLabel.setForeground(new Color(254,232,1));
        } else {
            timerLabel.setForeground(new Color(136,4,37));
        }
    }
    
    private void timeExpired() {
        countdownTimer.stop();
        totalQuestions++;
        feedbackLabel.setText(
            "Time up!  The answer was: " + currentDecimalValue);
        feedbackLabel.setForeground(new Color(136,4,37));
        scoreLabel.setText("Final Score: " + score + " / " + totalQuestions);
        
        submitButton.setEnabled(false);
        answerField.setEnabled(false);
    }

    private void restartTimer() {
        countdownTimer.stop();
        timeLeft = TIME_PER_QUESTION;
        updateTimerLabel();
        countdownTimer.start();
    }

    private void loadNewQuestion() {
        currentDecimalValue = random.nextInt(256);

        String binary = Integer.toBinaryString(currentDecimalValue);
        String padded = String.format("%8s", binary).replace(' ', '0');

        binaryLabel.setText(padded);
        feedbackLabel.setForeground(new Color(254,232,1));
        feedbackLabel.setText("Enter the decimal value above");
        answerField.setText("");
        answerField.requestFocus();
        restartTimer();
    }
       
    
    private void checkAnswer() {
        String input = answerField.getText().trim();

        if (input.isEmpty()) {
            feedbackLabel.setText("Please type an answer first.");
            feedbackLabel.setForeground(new Color(180, 120, 0));
            return;
        }

        try {
            int userAnswer = Integer.parseInt(input);
            countdownTimer.stop();
            totalQuestions++;

            int correctAnswer   = currentDecimalValue;
            String correctBinary = binaryLabel.getText();
            int timeTaken       = TIME_PER_QUESTION - timeLeft;

            if (userAnswer == currentDecimalValue) {
                score++;
                feedbackLabel.setText(
                    "Correct!  " + binaryLabel.getText()
                    + "  =  " + currentDecimalValue
                    + "  (" + (TIME_PER_QUESTION - timeLeft) + "s)"
                );
                feedbackLabel.setForeground(new Color(75,255,33));
                scoreLabel.setText("Score: " + score + " / " + totalQuestions);
                submitButton.setEnabled(false);
                answerField.setEnabled(false);

                Timer delay = new Timer(1500, e -> {
                    submitButton.setEnabled(true);
                    answerField.setEnabled(true);
                    loadNewQuestion();
                });
                delay.setRepeats(false);
                delay.start();

            } else {
                    countdownTimer.stop();
                    submitButton.setEnabled(false);
                    answerField.setEnabled(false);
                    feedbackLabel.setForeground(new Color(136,4,37));                        
                    feedbackLabel.setText("Dumbass the answer was " + currentDecimalValue);
                    scoreLabel.setText("Final Score: " + score + " / " + totalQuestions);   
            }

        } catch (NumberFormatException ex) {
            feedbackLabel.setText("Enter a whole number between 0 and 255.");
            feedbackLabel.setForeground(new Color(85,234,212));
        }
    }
        
    private void resetGame() {
        countdownTimer.stop();
        score = 0;
        totalQuestions = 0;
        scoreLabel.setText("Score: 0 / 0");
        feedbackLabel.setText(" ");
        answerField.setEnabled(true);
        submitButton.setEnabled(true);
        loadNewQuestion();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel binaryLabel;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
